Cora:
  seed: 4
  cl_lr: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feat_rate_1: 0.3
  drop_feat_rate_2: 0.4
  tau: 0.4
  cl_num_epochs: 800
  weight_decay: 0.00001
  eps: 0.01
  alpha: 200
  beta: 0.01
  lamb: 0

Pubmed:
  seed: 4
  cl_lr: 0.0005
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feat_rate_1: 0.0
  drop_feat_rate_2: 0.2
  tau: 0.7
  cl_num_epochs: 800
  weight_decay: 0.00001
  eps: 0.01
  alpha: 200
  beta: 0.01
  lamb: 0

Physics:
   seed: 1
   cl_lr: 0.01
   num_hidden: 128
   num_proj_hidden: 64
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.4
   drop_edge_rate_2: 0.1
   drop_feat_rate_1: 0.1
   drop_feat_rate_2: 0.4
   tau: 0.5
   cl_num_epochs: 1500
   weight_decay: 0.00001
   eps: 0.01
   alpha: 50
   beta: 0.001
   lamb: 0

ogbn-arxiv:
  seed: 4
  cl_lr: 0.0005
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feat_rate_1: 0.
  drop_feat_rate_2: 0.
  tau: 0.4
  cl_num_epochs: 400
  weight_decay: 0.00001
  eps: 0.01
  alpha: 50
  beta: 0.0011
  lamb: 0