# MUTAG:
#     cl_lr: 0.0005
#     num_hidden: 128
#     num_proj_hidden: 128
#     drop_edge_rate_1: 0.3
#     drop_edge_rate_2: 0.4
#     drop_feat_rate_1: 0.3
#     drop_feat_rate_2: 0.2
#     tau: 0.4
#     cl_num_epochs: 400
#     weight_decay: 0.00001
# PROTEINS:
#   drop_edge_rate_1: 0.4
#   drop_edge_rate_2: 0.1
#   drop_feat_rate_1: 0.0
#   drop_feat_rate_2: 0.2
#   tau: 0.7
#   cl_lr: 0.001
#   weight_decay: 0.00001
#   cl_num_epochs: 1500
#   num_hidden: 256
#   num_proj_hidden: 256

MUTAG:
  cl_lr: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  drop_edge_rate_1: 0.
  drop_edge_rate_2: 0.1
  drop_feat_rate_1: 0.
  drop_feat_rate_2: 0.1
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.1
  tau: 0.4
  cl_num_epochs: 100
  weight_decay: 0.00001
PROTEINS:
  drop_edge_rate_1: 0.
  drop_edge_rate_2: 0.1
  drop_feat_rate_1: 0.
  drop_feat_rate_2: 0.1
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.1
  tau: 0.7
  cl_lr: 0.001
  weight_decay: 0.00001
  cl_num_epochs: 100
  num_hidden: 256
  num_proj_hidden: 256
ogbg-molhiv:
  drop_edge_rate_1: 0.
  drop_edge_rate_2: 0.1
  drop_feat_rate_1: 0.
  drop_feat_rate_2: 0.1
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.1
  tau: 0.7
  cl_lr: 0.01
  weight_decay: 0.00001
  cl_num_epochs: 100
  num_hidden: 32
  num_proj_hidden: 32
